apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: runtime
spec:
  order:
  - group:
      - id: "io.quarkus.buildpacks.buildpack"
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
  stack:
    name: runtime
    kind: ClusterStack
  store:
    name: runtime
    kind: ClusterStore
  tag: 'ghcr.io/halkyonio/quarkus-builder:jvm'