apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: image
spec:
  params:
    - name: image_prefix
      default: some-default-prefix-

  imagePath: .status.latestImage

  template:
    apiVersion: kpack.io/v1alpha2
    kind: Image
    metadata:
      name: $(workload.metadata.name)$
    spec:
      tag: $(params.image_prefix)$/$(workload.metadata.name)$
      serviceAccountName: $(params.service_account)$
      builder:
        kind: ClusterBuilder
        name: $(params.kpack_cluster_builder)$
      source:
        blob:
          url: $(sources.source.url)$
      build:
        env: $(workload.spec.build.env)$
