#@ load("@ytt:data", "data")
#@ load("helpers.lib.yml", "img")

---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: runtime
spec:
  sources:
    - image: #@ img("buildpacks-quarkus-builder:jvm")