#@ load("@ytt:data", "data")
#@ load("helpers.lib.yml", "img")

---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: runtime
spec:
  id: "io.quarkus.buildpacks.stack.jvm"
  buildImage:
    image: #@ img("buildpacks-quarkus-run:jvm")
  runImage:
    image: #@ img("buildpacks-quarkus-build:jvm")