apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: runtime
spec:
  id: "io.quarkus.buildpacks.stack.jvm"
  buildImage:
    image: "codejive/buildpacks-quarkus-run:jvm"
  runImage:
    image: "codejive/buildpacks-quarkus-build:jvm"