# https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-intellij-extension-getting-started.html
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-tap-petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-tap-petclinic
spec:
  # tanzu apps workload update spring-tap-petclinic --annotation "autoscaling.knative.dev/scaleDownDelay=15m"
  # params:
  # - name: annotations
  #   value:
  #     autoscaling.knative.dev/scaleDownDelay: 15m
  #     autoscaling.knative.dev/minScale: "1"

  # tanzu apps workload update spring-tap-petclinic --annotation "autoscaling.knative.dev/scaleDownDelay=15m" --env "SPRING_PROFILES_ACTIVE=postgresql
  # env:
  #   - name: SPRING_PROFILES_ACTIVE
  #     value: postgres

  # tanzu services instances list -o wide
  # tanzu apps workload update spring-tap-petclinic --service-ref "db=sql.tanzu.vmware.com/v1:Postgres:tap-demo:postgres-db"
  #
  # serviceClaims:
  #   - name: db
  #     ref:
  #       apiVersion: sql.tanzu.vmware.com/v1
  #       kind: Postgres
  #       name: postgres-db
  source:
    git:
      url: https://github.com/halkyonio/spring-tap-petclinic.git
      ref:
        branch: main