apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: kubernetes-dashboard
  namespace: pkg-demo
spec:
  serviceAccountName: carvel-package
  packageRef:
    refName: kubernetes-dashboard.halkyonio.io
    versionSelection:
      constraints: 0.1.0
  values:
    - secretRef:
        name: k8s-ui-values