#@ load("@ytt:data", "data")  # for reading data values (generated via ytt's data-values-schema-inspect mode).
#@ load("@ytt:yaml", "yaml")  # for dynamically decoding the output of ytt's data-values-schema-inspect
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ "kubernetes-dashboard.halkyonio.io." + data.values.version
  namespace: pkg-demo
spec:
  version: #@ data.values.version
  refName: kubernetes-dashboard.halkyonio.io
  releaseNotes: |
    Initial release of the Kubernetes Helm dashboard
  valuesSchema:
    openAPIv3: #@ yaml.decode(data.values.openapi)["components"]["schemas"]["dataValues"]
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: #@ "ghcr.io/halkyonio/packages/kubernetes-dashboard:" + data.values.version
      template:
        - ytt:
            paths:
              - "config/"
              - values.yml
        - kbld:
            paths:
              - '-'
              - .imgpkg/images.yml
      deploy:
        - kapp: {}