---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carvel-package
  namespace: pkg-demo
imagePullSecrets:
  - name: ghcr-creds
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carvel-package
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: carvel-package
subjects:
  - kind: ServiceAccount
    name: carvel-package
    namespace: pkg-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: carvel-package