apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: runtime
spec:
  id: "io.quarkus.buildpacks.stack.jvm"
  buildImage:
    image: "95.217.159.244:32500/redhat-buildpacks/quarkus:build"
  runImage:
    image: "95.217.159.244:32500/redhat-buildpacks/quarkus:run"