apiVersion: kpack.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: runtime
spec:
  order:
  - group:
      - id: "io.quarkus.buildpacks.buildpack"
  serviceAccountRef:
    name: canonical-registry-serviceaccount
    namespace: kpack
  stack:
    name: runtime
    kind: ClusterStack
  store:
    name: runtime
    kind: ClusterStore
  tag: '95.217.159.244:32500/runtime'