#@data/values
---
service_account_name: default
namespace: tap-demo
image_prefix: ghcr.io/halkyonio
runtime:
  deliverable_type: quarkus
  kubernetes_io_partof: quarkus-java-web-app
buildpack:
  kpack_cluster_builder: runtime
workload:
  name: quarkus-app
github:
  url: https://github.com/halkyonio/quarkus-tap-petclinic.git
  ref: main
